[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.38.14",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]
